(set-reg 0 1)
(set-reg 3 10)
(memwrite-bf (return-num 1))

(print-string "current: ")
(print-bf (add-bf (return-num 0x30) (memread)))
(print-string "\n")

(while-bf (return-num 1)
          (mov-reg 1 0)
          (set-reg 4 0)
          (while-bf (return-reg 1)
                    (dec-reg 1)
                    (add-bf (memread) (memread) (return-reg 4))
                    (mov-reg 2 return-value-reg)
                    (div-regs 2 3 4 5)
                    (memwrite 5)
                    (memseek-up-bf (return-num 1)))
          (if-bf (return-reg 4)
                 (str (memwrite 4)
                      (inc-reg 0))
                 (memseek-down-bf (return-num 1)))
          (mov-reg 1 0)
          (while-bf (return-reg 1)
                    (dec-reg 1)
                    (print-bf (add-bf (return-num 0x30) (memread)))
                    (memseek-down-bf (return-num 1)))
          (print-string "\n"))